In [1]:
import numpy as np
from scipy.sparse import csr_matrix

x = [[1, 0, 0, 0, 2],
     [0, 3, 0, 4, 0],
     [0, 0, 0, 0, 0],
     [5, 0, 0, 6, 0]]
x = np.asarray(x)
csr = csr_matrix(x)

In [4]:
csr.todense()

matrix([[1, 0, 0, 0, 2],
        [0, 3, 0, 4, 0],
        [0, 0, 0, 0, 0],
        [5, 0, 0, 6, 0]], dtype=int64)

In [16]:
csr.data

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [15]:
csr.indices

array([0, 4, 1, 3, 0, 3], dtype=int32)

In [13]:
csr.indptr

array([0, 2, 4, 4, 6], dtype=int32)

In [10]:
from scipy.sparse import dok_matrix

dok = dok_matrix(x)
dok.values()

dict_values([1, 2, 3, 4, 5, 6])

In [14]:
for i, (b, e) in enumerate(zip(csr.indptr, csr.indptr[1:])):
    for idx in range(b, e):
        j = csr.indices[idx]
        d = csr.data[idx]
        print('({}, {}) = {}'.format(i, j, d))

(0, 0) = 1
(0, 4) = 2
(1, 1) = 3
(1, 3) = 4
(3, 0) = 5
(3, 3) = 6


In [39]:
def csr_mat_slicing(x, row, col):
    data = x.data
    indices = x.indices
    indptr = x.indptr
    
    b_indx = indptr[row]
    e_indx = indptr[row+1]
    row_values = data[b_indx:e_indx]
    col_indices = indices[b_indx:e_indx]
    
    return row_values[np.where(col_indices == col)[0]]

csr_mat_slicing(csr, 1,2)

array([], dtype=int64)

In [30]:
indptr

array([0, 2, 4, 4, 6], dtype=int32)

In [35]:
csr.todense()

matrix([[1, 0, 0, 0, 2],
        [0, 3, 0, 4, 0],
        [0, 0, 0, 0, 0],
        [5, 0, 0, 6, 0]], dtype=int64)